### ISSUE TITLE
Keep comments and basic file structure when using boilerplates

### ISSUE THREAD

**Issue by amenk** [nordcode/robo-parameters#4]
The dotenv writer removes comments and empty lines which are useful, for example in dotenv files, when using them as boiler plate.

What do you think? How can this be added?

**Comment by HenningCash** [comment]
Sounds very difficult. Most parsers/readers use either external libraries or PHP internal functions which ignore whitespace and comments. So writing back comments and empty lines requires own implementations of these parsers or re-parsing the written files. I don't think it's wort the effort, sorry.  
Could you give an example where you still need the comments and/or whitespace?

**Comment by amenk** [comment]
Cases where we commented the config file with additional information :-)
But you might be right, might not be wort the effort...

**Comment by HenningCash** [comment]
So I will close this for now, but if you have an idea how to implement this easily reopen the issue or create a PR :wink:
